name: CI

on:
  push:
    branches: [ master, "**" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os_short }} x86 + x86_64)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        sm_version:
          - "1.12-dev"
        include:
          - os: ubuntu-latest
            os_short: linux
          - os: windows-latest
            os_short: win

    steps:
      - name: Checkout webcon
        uses: actions/checkout@v4
        with:
          path: webcon
          submodules: recursive

      - name: Checkout SourceMod
        uses: actions/checkout@v4
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_version }}
          submodules: recursive
          path: sourcemod

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ambuild
        run: |
          python -m pip install --upgrade pip wheel
          pip install git+https://github.com/alliedmodders/ambuild

      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-multilib g++-multilib

      - name: Add msbuild to PATH (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - name: Set up MSVC environment (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          :: See https://github.com/microsoft/vswhere/wiki/Find-VC
          for /f "usebackq delims=*" %%i in (`vswhere -latest -property installationPath`) do (
            call "%%i"\Common7\Tools\vsdevcmd.bat -arch=x86 -host_arch=x64
          )

          :: Loop over all environment variables and make them global.
          for /f "delims== tokens=1,2" %%a in ('set') do (
            echo>>"%GITHUB_ENV%" %%a=%%b
          )

      - name: Configure
        working-directory: webcon
        shell: bash
        run: |
          mkdir build && cd build
          python ../configure.py --targets x86,x86_64 --enable-optimize \
            --sm-path "${GITHUB_WORKSPACE}/sourcemod"

      - name: Build
        working-directory: webcon/build
        shell: bash
        run: ambuild

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: webcon-sm${{ matrix.sm_version }}-${{ matrix.os_short }}
          path: webcon/build/package
